name: CrafterTracker
main: tmc.CrafterTracker.CrafterTrackerPlugin
version: 0.01

commands:
  sessioninfo:
    description: Display your session info.
    permissions: CrafterTracker.sessioninfo
    usage: /<command>
  warn:
    description: Warn a user
    permissions: CrafterTracker.warn
    usage: /<command> [player] [severity] [message]
  score:
    description: Displays a given player's score.
    permissions: CrafterTracker.score
    usage: /<command> [player(Optional)]
  playerinfo:
    description: Shows a player's server join date and average play time.
    permissions: CrafterTracker.playerinfo
    usage: /<command> [player(Optional)]
    aliases: [pi, pinfo]
  warningsfor:
    description: Displays a player's warnings.
    permissions: CrafterTracker.warningsfor
    usage: /<command> [player]
    aliases: [wf, wfor]
  acknowledge:
    description: Acknowledge a warning with identification number.
    permissions: CrafterTracker.acknowledge
    usage: /<command> [warningId]
    aliases: [ack]