name: CrafterTracker
main: tmc.CrafterTracker.CrafterTrackerPlugin
version: 0.01

commands:
  sessioninfo:
    description: Display your session info.
    permissions: CrafterTracker.sessioninfo
    usage: /<command>
  warn:
    description: Warn a user
    permissions: CrafterTracker.warn
    usage: /<command> [player] [severity] [message]
  score:
    description: Displays a given player's score.
    permissions: CrafterTracker.score
    usage: /<command> [player(Optional)]